useFMTitle: true
useNoteTitleForLink: true
mermaid: true
useKatex: true
dev:
    enablePreviewV2: true
site:
    copyAssets: true
    siteHierarchies:
        - root
    siteRootDir: docs
    siteUrl: 'https://100devsresources.netlify.app/'
    usePrettyRefs: true
    title: 100Devs Resources
    description: We Go Get!
    siteLastModified: true
    gh_edit_branch: main
version: 4
commands:
    lookup:
        note:
            selectionMode: extract
            confirmVaultOnCreate: false
            leaveTrace: false
            bubbleUpCreateNew: true
    randomNote: {}
    insertNote:
        initialValue: templates
    insertNoteLink:
        aliasMode: none
        enableMultiSelect: false
    insertNoteIndex:
        enableMarker: false
workspace:
    dendronVersion: 0.70.0
    vaults:
        -
            fsPath: vault
    journal:
        dailyDomain: daily
        name: journal
        dateFormat: y.MM.dd
        addBehavior: childOfDomain
    scratch:
        name: scratch
        dateFormat: y.MM.dd.HHmmss
        addBehavior: asOwnDomain
    graph:
        zoomSpeed: 1
    enableAutoCreateOnDefinition: false
    enableXVaultWikiLink: false
    enableRemoteVaultInit: true
    workspaceVaultSyncMode: noCommit
    enableAutoFoldFrontmatter: true
    maxPreviewsCached: 10
    maxNoteLength: 204800
    task:
        name: ''
        dateFormat: ''
        addBehavior: childOfCurrent
        statusSymbols:
            '': ' '
            wip: w
            done: x
            assigned: a
            moved: m
            blocked: b
            delegated: l
            dropped: d
            pending: 'y'
        prioritySymbols:
            H: high
            M: medium
            L: low
        todoIntegration: false
        createTaskSelectionType: selection2link
    enableUserTags: true
    enableHashTags: true
preview:
    enableFMTitle: true
    enableNoteTitleForLink: true
    enableMermaid: true
    enablePrettyRefs: true
    enableKatex: true
