# uncomment to preview locally
#theme: "dendron-jekyll"
remote_theme: dendronhq/dendron-jekyll
title: 100Devs_Resources
logo: '/assets/images/logo.png'
exclude:
  [
    'node_modules/',
    '*.gemspec',
    '*.gem',
    'Gemfile',
    'Gemfile.lock',
    'package.json',
    'package-lock.json',
    'script/',
    'LICENSE.txt',
    'lib/',
    'bin/',
    'README.md',
    'Rakefile',
    '*/dendron.template.release.md',
  ]
footer_content: ''

gh_edit_link: false

siteIndex: '100Devs-resources.md'

# seo
tagline: 'We Go Get'
description: 'An idiosyncratic collections of resources for the #100Devs / Learn With Leon community.'
twitter:
  card: summary
  username: bomboloni
author:
  twitter: Bomboloni

defaults:
  - scope:
      path: 'notes' # an empty string here means all files in the project
    values:
      layout: 'default'
      image: '/assets/images/logo.png'
